lib/class-wp-json-base-posts-controller.php, lib/class-wp-json-posts-controller.php, tests/test-json-posts-controller.php
=> Resolve regressions in Posts Controller

lib/class-wp-json-response.php, lib/class-wp-json-server.php, tests/class-wp-test-json-testcase.php, tests/test-json-terms-controller.php, tests/test-json-users-controller.php
=> WP_Json_Server::dispatch() should always return a WP_JSON_Response

README.md
Updating timeline note to reflect the current status from https://github.com/WP-API/WP-API/issues/571
=> Update Timeline note

lib/class-wp-json-taxonomies-controller.php, tests/test-json-taxonomies-controller.php
Fixes #825 and adds unit test.
=> Adds missing description field to the Taxonomy response

lib/class-wp-json-posts-controller.php, tests/test-json-posts-controller.php
=> Add `featured_image` attribute for post types that support `thumbnails`

lib/class-wp-json-posts-controller.php
=> Don't noop `future` status. It's confusing

lib/class-wp-json-posts-controller.php
Missed cleaning this up from #836
=> Remove unused $request parameter from prepare_links method.

.travis.yml
Travis environment doesn't support it
See #846
=> Disable PHP 5.2 testing for now

docs/routes/routes.md
We get constant questions about why meta isn't accessible. Let's improve the documentation here a bit so it's easier to understand, and we can avoid having issues constantly filed.
Fixes #857
=> Add documentation on why meta is unavailable

.travis.yml
Reverts #849 and fixes #846.
Issue resolved in https://github.com/travis-ci/travis-cookbooks/pull/451
=> Re-enable PHP 5.2 for Travis builds.

lib/class-wp-json-comments-controller.php, lib/class-wp-json-terms-controller.php, lib/class-wp-json-users-controller.php, tests/test-json-comments-controller.php, tests/test-json-terms-controller.php, tests/test-json-users-controller.php
=> Add `link` field to Users, Comments and Terms

tests/test-json-comments-controller.php, tests/test-json-terms-controller.php, tests/test-json-users-controller.php
=> Fix flipped assertions

lib/class-wp-json-posts-controller.php
Fixes this build failure
https://travis-ci.org/WP-API/WP-API/builds/51738714
Related #904
=> Add missing break statement

lib/endpoints/class-wp-json-posts-controller.php, tests/test-json-pages-controller.php, tests/test-json-posts-controller.php
=> Always include `guid` in Post and Page schemas

lib/endpoints/class-wp-json-posts-controller.php
=> Allow post type attributes to be set based on presence in schema

lib/endpoints/class-wp-json-post-types-controller.php, plugin.php, tests/test-json-post-types-controller.php
=> Expose post type data at `/types`

lib/endpoints/class-wp-json-posts-controller.php, tests/class-wp-test-json-post-type-controller-testcase.php, tests/test-json-pages-controller.php
=> Add `template` parameter to Page response

lib/endpoints/class-wp-json-taxonomies-controller.php, plugin.php, tests/test-json-taxonomies-controller.php
=> Clean up taxonomies controller tests by running through dispatch; add schema

lib/endpoints/class-wp-json-posts-controller.php
This is a lot of whitespace changes, but mainly things that don't need to be on separate branches.
Non-whitespace changes only: https://github.com/WP-API/WP-API/pull/936/files?w=1
=> Tweak the post controller

plugin.php
=> Switch CORS headers callback to new action

lib/endpoints/class-wp-json-comments-controller.php, tests/test-json-comments-controller.php
=> Add `author_ip`, `author_user_agent` and `karma` fields to Comment

tests/test-json-comments-controller.php
=> Explicitly test that these additional comment fields aren't present

lib/endpoints/class-wp-json-posts-controller.php, lib/infrastructure/class-wp-json-server.php
=> Use real URLs instead of query_params attribute

lib/endpoints/class-wp-json-posts-controller.php, lib/endpoints/class-wp-json-taxonomies-controller.php, lib/endpoints/class-wp-json-terms-controller.php, lib/endpoints/class-wp-json-users-controller.php, tests/test-json-attachments-controller.php, tests/test-json-posts-controller.php, tests/test-json-taxonomies-controller.php, tests/test-json-terms-controller.php, tests/test-json-users-controller.php
This adds permissions logic abstraction for the remaining classes (with the exception of meta).
=> Permission abstractions 2

lib/endpoints/class-wp-json-users-controller.php, tests/test-json-users-controller.php
=> Throw error if requesting user doesn't have capability for context

lib/endpoints/class-wp-json-post-statuses-controller.php, plugin.php, tests/test-json-post-statuses-controller.php
=> `/wp/statuses` endpoint, modeled after `/wp/types`

lib/endpoints/class-wp-json-post-types-controller.php, tests/test-json-post-types-controller.php
=> Turn post types from array to object, with name as key

lib/endpoints/class-wp-json-posts-controller.php, tests/test-json-posts-controller.php
=> Setting a post to be sticky AND password protected should fail

lib/endpoints/class-wp-json-users-controller.php, tests/test-json-users-controller.php
=> Use appropriate functions when creating users on multisite

lib/endpoints/class-wp-json-attachments-controller.php, lib/endpoints/class-wp-json-comments-controller.php, lib/endpoints/class-wp-json-post-statuses-controller.php, lib/endpoints/class-wp-json-post-types-controller.php, lib/endpoints/class-wp-json-posts-controller.php, lib/endpoints/class-wp-json-taxonomies-controller.php, lib/endpoints/class-wp-json-terms-controller.php, lib/endpoints/class-wp-json-users-controller.php
=> Define context in which each schema field appears

lib/endpoints/class-wp-json-controller.php, lib/endpoints/class-wp-json-users-controller.php, tests/test-json-users-controller.php
=> Use schema abstraction to limit which user fields are exposed per context

lib/endpoints/class-wp-json-post-statuses-controller.php, lib/endpoints/class-wp-json-post-types-controller.php, lib/endpoints/class-wp-json-taxonomies-controller.php
=> Run Statuses, Types, and Taxonomies through our context filter

lib/endpoints/class-wp-json-terms-controller.php
=> Run Terms controller through schema context filter

lib/endpoints/class-wp-json-posts-controller.php, tests/class-wp-test-json-post-type-controller-testcase.php, tests/test-json-posts-controller.php
=> Don't allow contributors to set sticky on posts

CHANGELOG.md, lib/class-wp-json-posts.php, plugin.php, tests/test-json-post-revisions.php
=> Fix revision access for master

plugin.php, tests/test-json-plugin.php
Fixes #1057 and adds testing to ensure it doesn't happen again.
=> Fix error with OPTIONS requests

lib/endpoints/class-wp-json-comments-controller.php, tests/test-json-comments-controller.php
Converts Comment author object to flat Comment attributes
Also changes response object based on declared context
Fixes #1022
See #894
=> Prefer destructured objects over nested sub-objects

extras.php, lib/endpoints/class-wp-json-comments-controller.php, lib/endpoints/class-wp-json-controller.php, lib/endpoints/class-wp-json-revisions-controller.php, lib/endpoints/class-wp-json-taxonomies-controller.php, lib/endpoints/class-wp-json-terms-controller.php, lib/endpoints/class-wp-json-users-controller.php, lib/infrastructure/class-wp-json-request.php, lib/infrastructure/class-wp-json-server.php, plugin.php, tests/bootstrap.php, tests/helper.php, tests/test-json-attachments-controller.php, tests/test-json-comments-controller.php, tests/test-json-pages-controller.php, tests/test-json-plugin.php, tests/test-json-posts-controller.php, tests/test-json-server.php, tests/test-json-taxonomies-controller.php
Pinking shears and code standards spacing fixes.
=> Whitespace Fixes

.scrutinizer.yml, .travis.yml
Testing to try to get PHPUnit code coverage to display in Travis CI and Scrutinizer.
=> Add phpunit code coverage to Travis CI config file.

tests/test-json-terms-controller.php
Adds additional tests for expected error responses for changes in #1048
=> Increase Terms Controller test coverage

lib/endpoints/class-wp-json-posts-controller.php, lib/endpoints/class-wp-json-revisions-controller.php, lib/endpoints/class-wp-json-terms-controller.php, tests/test-json-revisions-controller.php
=> Drop revision embedding from posts controller; link instead

README.md
=> Add security section to our README

lib/endpoints/class-wp-json-attachments-controller.php, lib/endpoints/class-wp-json-comments-controller.php, lib/endpoints/class-wp-json-controller.php, lib/endpoints/class-wp-json-posts-controller.php, lib/endpoints/class-wp-json-terms-controller.php, lib/endpoints/class-wp-json-users-controller.php, lib/infrastructure/class-wp-json-response.php, lib/infrastructure/class-wp-json-server.php, plugin.php, tests/test-json-attachments-controller.php, tests/test-json-terms-controller.php, tests/test-json-users-controller.php
Fixes #859.
@WP-API/amigos What do you think of the approach here? There's a wee bit of duplication needed in that we're now replicating a small part of the server, but I don't think that's too big of an issue.
If we're :+1: on the approach, I'll apply the same to our other collections too.
=> Display links in collections

lib/infrastructure/class-wp-json-request.php
This means clients can get lots of info at once, rather than one at a time,
see https://github.com/WP-API/WP-API/pull/1128#issuecomment-95405670
=> Show all the invalid param errors at once

plugin.php
We should've done this a while ago.
=> Change `develop` to 2.0-alpha.

lib/endpoints/class-wp-json-posts-controller.php, tests/class-wp-test-json-post-type-controller-testcase.php, tests/test-json-posts-controller.php
=> Only return 201 on Create. Update should be 200

lib/infrastructure/class-wp-rest-request.php
Not sure but i think this should be renamed too #1151
=> json_ to rest_

lib/endpoints/class-wp-rest-posts-controller.php
but isn't used anway afaik as of #716 this got removed entirely ?
=> accept_json got renamed to accept_rest

Gruntfile.js, bin/phpcs.sh, package.json
=> In addition to Coding Standards, test for syntax errors

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
=> Add pagination headers to term collection response

lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-users-controller.php
=> Pagination headers for `GET /wp/v2/users`

README.md
=> Update Readme in master

lib/endpoints/class-wp-rest-controller.php
It's a standard method
Fixes #1173
=> Add `prepare_item_for_database()` method to base controller class

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-controller.php, lib/endpoints/class-wp-rest-meta-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-revisions-controller.php, lib/endpoints/class-wp-rest-taxonomies-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php
Mainly return types in a standardized format
=> Fix lots of doc blocks

lib/endpoints/class-wp-rest-comments-controller.php, tests/test-rest-comments-controller.php
=> Pagination headers for comment collection queries

lib/endpoints/class-wp-rest-controller.php, lib/endpoints/class-wp-rest-terms-controller.php
=> Declare term collection params so they can be exposed

lib/endpoints/class-wp-rest-comments-controller.php, tests/test-rest-comments-controller.php
=> Declare supported arguments for comments collection queries

lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-users-controller.php
=> Declare supported arguments for user collection queries

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
=> Only permit querying by parent term when tax is hierarchical

lib/endpoints/class-wp-rest-comments-controller.php, tests/test-rest-comments-controller.php
=> Rename `post_name` to `post_slug`

.coveralls.yml, .travis.yml, composer.json
Don't merge this one yet, just testing on this branch.
=> Use Coveralls for code coverage

lib/endpoints/class-wp-rest-post-statuses-controller.php, tests/test-rest-post-statuses-controller.php
=> Add links to the status(es) responses

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
=> Handle term parent on update / create term

tests/bootstrap.php, tests/test-rest-comments-controller.php, tests/test-rest-posts-controller.php, tests/test-rest-revisions-controller.php, tests/test-rest-terms-controller.php
If we ever get to the impossibly high number and our tests fail
crypically, this will be easier to fix in one fell swoop
=> Use a constant every time we want an impossibly high number

lib/endpoints/class-wp-rest-comments-controller.php, tests/test-rest-comments-controller.php
=> Return full comment object when deleting comment

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
=> Return full term object when deleting term

.travis.yml, Gruntfile.js, bin/phpcs.sh, composer.json, extras.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-revisions-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php, lib/infrastructure/class-wp-rest-request.php, lib/infrastructure/class-wp-rest-response.php, package.json, tests/class-wp-test-rest-post-type-controller-testcase.php, tests/test-rest-posts-controller.php, tests/test-rest-server.php, tests/test-rest-users-controller.php
=> Restore WP Coding Standards on builds

lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-users-controller.php
=> Add check when creating a user to verify the provided role is valid.

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-meta-controller.php, lib/endpoints/class-wp-rest-post-statuses-controller.php, lib/endpoints/class-wp-rest-post-types-controller.php, lib/endpoints/class-wp-rest-revisions-controller.php, lib/endpoints/class-wp-rest-taxonomies-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-attachments-controller.php, tests/test-rest-comments-controller.php, tests/test-rest-post-statuses-controller.php, tests/test-rest-post-types-controller.php, tests/test-rest-revisions-controller.php
This is wrapping up the reaminder of the controller classes the additional fields compat
=> Add additional fields functions for the rest of the controllers

plugin.php
WIP: (not ready for review/merge).
1204ab4 contains one possible fix, but I am still thinking about the best approach.
Would fix #1019
=> Remove filters that duplicate adding and getting meta functionality.

.travis.yml, composer.json
Let's try this thing. Coveralls doesn't support non-master branches as main, so let's give this a whirl.
=> Try Codecov for coverage

README.md
=> Update Scrutinizer badge

bin/phpcs.sh, lib/endpoints/class-wp-rest-controller.php, lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-attachments-controller.php, tests/test-rest-comments-controller.php, tests/test-rest-post-statuses-controller.php, tests/test-rest-post-types-controller.php, tests/test-rest-revisions-controller.php, tests/test-rest-users-controller.php
This will get WordPress Coding Standards to fail our builds again.
=> If `phpcs` failed, hard fail

.coveralls.yml
We don't need it, so let's remove it.
=> Remove coveralls config file

extras.php, lib/endpoints/class-wp-rest-comments-controller.php, tests/test-rest-comments-controller.php
=> Add `author_avatar_url` to the Comment response and schema

lib/endpoints/class-wp-rest-attachments-controller.php
=> Clarify what `Content-Disposition` header actually needs to be

lib/endpoints/class-wp-rest-controller.php, tests/class-wp-rest-test-controller.php, tests/test-rest-controller.php
This default is then use for the default arg value also. We could use this in
communicate to clients what th default value will be.
=> Ability to specify a default in the schema

Gruntfile.js
This will run phpcs, lint and phpunit - all the stuff that's run on GitHub
=> Add a `grunt test` task to run all tests

README.md
Shows
[![codecov.io](http://codecov.io/github/WP-API/WP-API/coverage.svg?branch=develop)](http://codecov.io/github/WP-API/WP-API?branch=develop)
=> Show off our awesome coverage with a badge

bin/readme.txt, bin/release.sh
This adds some build tools, as well as checking the actual readme.txt on the repo in. Already used this for making the latest `rest-api` release, filing as a PR for posterity's sake. :)
=> Add release tools

lib/endpoints/class-wp-rest-attachments-controller.php, tests/test-rest-attachments-controller.php
Props @picklepete, fixes #1437.
=> Use correct attribute when updating attachment post

README.md
Also adds a link to instructions for using Subversion's `trunk` branch for development.
=> Update the search example to again use `filter`.

composer.json
=> Specify a version for WPCS in composer.json

lib/endpoints/class-wp-rest-controller.php
=> Typo fix unintentially->unintentionally

lib/infrastructure/class-wp-rest-server.php
Note, see: https://github.com/WP-API/WP-API/issues/1549
* Add missing hook docs
* Some language and punctuation cleanup
=> Add hook docs: lib/infrastructure/class-wp-rest-server.php

lib/endpoints/class-wp-rest-taxonomies-controller.php
* Docs for `rest_prepare_taxonomy`
=> Add hook docs for lib/endpoints/class-wp-rest-taxonomies-controller.php

lib/endpoints/class-wp-rest-comments-controller.php, tests/test-rest-comments-controller.php
=> Set comment author details from current user

lib/endpoints/class-wp-rest-revisions-controller.php
In prepare_item_for_response method of WP_REST_Revisions_Controller class.
=> Amends PHPDoc for $post parameter.

lib/endpoints/class-wp-rest-meta-controller.php
* Add hook doc for `rest_prepare_meta_value`
=> Hood docs - lib/endpoints/class-wp-rest-meta-controller.php

plugin.php
Altered the conditional for 'permalink_structure' to cover subsites
of a multisite if applicable.
=> Added conditional check for multisite for `get_rest_url`

extras.php, lib/infrastructure/class-jsonserializable.php, lib/infrastructure/class-wp-http-response.php, lib/infrastructure/class-wp-http-responseinterface.php, lib/infrastructure/class-wp-rest-request.php, lib/infrastructure/class-wp-rest-response.php, lib/infrastructure/class-wp-rest-server.php, plugin.php
https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/
=> Core Docs standards

lib/endpoints/class-wp-rest-posts-controller.php
* Add hood docs where missing
* some language cleanup for consistency
=> Hook docs: lib/endpoints/class-wp-rest-posts-controller.php

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
=> Limit Scope and Fix PHPCS for #1581

lib/endpoints/class-wp-rest-posts-terms-controller.php, phpcs.ruleset.xml, tests/bootstrap.php
=> Fix tests with latest trunk

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
=> Handle falsy value from wp_count_terms, fixing fatal

lib/endpoints/class-wp-rest-controller.php
=> Make error message more helpful by specifying method to subclass

extras.php
Better File Header Documentation
- Adds @since 4.4.0
- Separates short and long descriptions
=> Better File Header Documentation

lib/endpoints/class-wp-rest-posts-controller.php
=> End comments in periods

compatibility-v1.php
In accordance with WP docs standards, this commit Adds Periods to Short, Long Dec and Inline Comments
=> Add Periods to Short, Long Dec and Inline Comments

lib/endpoints/class-wp-rest-meta-controller.php, lib/endpoints/class-wp-rest-posts-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php
Combines #1517, #1515, and #1512
=> Fix delete args

.travis.yml, bin/install-wp-tests.sh, plugin.php
=> Run tests against WP nightly and WP latest (4.3)

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
=> Properly handle parent=0 when 0 is a string

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
See https://github.com/WP-API/WP-API/commit/e4a9fecd57a72661a4de99f00754c9a90c32e675#commitcomment-14493584
From #1726
=> Change link relations to use https instead of http

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
Adds location header to the new term
Fixes #1751
=> Return 201 status code when creating a term

composer.json
v2.4.0, satisfied by WPCS requirements, has issues with it
=> Lock PHPCS to v2.3.4

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
=> Support for getting a post with a custom public status

tests/test-rest-posts-controller.php
=> Add test case for Post's meta links

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
Including `author`, `order`, `orderby` and `status`
See #924
=> Expose Post collection query params

lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-posts-terms-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php
=> Standardize declaration of `context` param for collections across controllers

lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-users-controller.php
It's more consistent with Posts
Fixes #1771
=> Default to wildcard when searching users

lib/endpoints/class-wp-rest-post-types-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-post-types-controller.php, tests/test-rest-posts-controller.php
=> Link Types to their Collections and vice versa

lib/endpoints/class-wp-rest-post-statuses-controller.php
This filter is consistent with other preparation filters
=> Add `rest_prepare_status` filter

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-revisions-controller.php, lib/endpoints/class-wp-rest-taxonomies-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php
* Pass `$response` variable, to more clearly communicate expected value
* PHPdoc clarifications and corrections
=> Make `prepare_*` filters more consistent

lib/endpoints/class-wp-rest-posts-controller.php
=> Add a helpful description to the `filter` argument

lib/endpoints/class-wp-rest-post-types-controller.php, tests/test-rest-post-types-controller.php
=> Add `edit` context for `wp/v2/types`; require `edit_posts` cap

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-controller.php, lib/endpoints/class-wp-rest-meta-controller.php, lib/endpoints/class-wp-rest-post-statuses-controller.php, lib/endpoints/class-wp-rest-post-types-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-posts-terms-controller.php, lib/endpoints/class-wp-rest-revisions-controller.php, lib/endpoints/class-wp-rest-taxonomies-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php
=> Make `description` strings available for translation

lib/endpoints/class-wp-rest-attachments-controller.php
=> Use `WP_REST_Request` internally in `WP_REST_Attachments_Controller`

lib/endpoints/class-wp-rest-comments-controller.php
=> Use `WP_REST_Request` internally in `WP_REST_Comments_Controller`

lib/endpoints/class-wp-rest-users-controller.php
=> Use `WP_REST_Request` internally in `WP_REST_Users_Controller`

lib/endpoints/class-wp-rest-posts-controller.php
=> Use `WP_REST_Request` internally in `WP_REST_Posts_Controller`

lib/endpoints/class-wp-rest-terms-controller.php
=> Use `WP_REST_Request` internally in `WP_REST_Terms_Controller`

lib/endpoints/class-wp-rest-users-controller.php
=> Don't include method and URL in internal `WP_REST_Request` (User)

lib/endpoints/class-wp-rest-terms-controller.php
=> Don't include method and URL in internal `WP_REST_Request` (Term)

tests/test-rest-posts-controller.php
=> Add test case for creating a post with empty password and sticky

tests/test-rest-posts-controller.php
=> `s/test_get_item_author_query/test_get_items_author_query`

lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-users-controller.php
=> Add `include` parameter to `GET /wp/v2/users`

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
=> Add `include` parameter to `GET /wp/v2/<taxonomy>`

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-pages-controller.php, tests/test-rest-posts-controller.php
Adds tests for Post and Page query params
See #924
=> Declare `parent` query param for Pages
