lib/class-wp-json-server.php
It's always referred to in `dispatch()`, so it needs to be set.
Fixes #740
=> Default `args` to an empty array

lib/class-wp-json-base-posts-controller.php, tests/test-json-posts-controller.php
Fixes #760
Only check if a post_type is being changed if the type parameter is set.
Fallback to the post_type of the post being updated when doing permission checks.
Includes unit test.
=> Do not require type parameter to be set when updating a Post

docs/routes/routes.md
The post type must be passed as a ```type``` parameter with the GET request, not as a query variable for for the ```filter``` parameter.
Post types are pulled from ```type``` parameter [here](https://github.com/WP-API/WP-API/blob/develop/lib/class-wp-json-posts.php#L206-L214) and any ```post_type``` query variable in the ```filter``` parameter is discarded [here](https://github.com/WP-API/WP-API/blob/develop/lib/class-wp-json-posts.php#L241).
```type``` parameter is already documented a little farther down in the docs.
=> Remove from docs the "post_type" filter parameter for /posts endpoint

lib/class-wp-json-server.php
Currently `json_post_dispatch` passes the response data and the request
object, whereas the `json_pre_dispatch` passes the response data (null), the
server and the request object.
These filters should be consistent.
=> Make json_pre_dispatch and json_post_dispatch consistent

tests/class-wp-test-json-controller-testcase.php, tests/test-json-posts-controller.php, tests/test-json-taxonomies-controller.php, tests/test-json-terms-controller.php, tests/test-json-users-controller.php
Fixes #793 
Added tearDown method to WP_Test_JSON_Controller_Testcase.
Removed any duplicate setUp logic from the classes that extended WP_Test_JSON_Controller_Testcase.
Removed any duplicate tearDown logic from the classes that extended WP_Test_JSON_Controller_Testcase.
=> Normalize our test classes setUP and tearDown methods

README.md
=> Readme clarifications.

lib/class-wp-json-base-posts-controller.php, tests/test-json-posts-controller.php
Fixes #788 
No longer passing $post by reference in `get_items()` method of Posts Controller, instead using an array to gather posts once they pass the permission check.
Added unit test to confirm logic is no longer flawed.  
This was not an issue in any of the other endpoint Controllers.
=> Correct /posts/ endpoint read post permission logic

lib/class-wp-json-users-controller.php, tests/test-json-users-controller.php
=> Expose basic author details when user has published posts

lib/class-wp-json-posts-controller.php, plugin.php
Removes legacy `json_register_post_type()` that was modifying post_type attributes in conflict with #820.  The `json_register_post_type()` function was causing additional revision routes to be registered that are not supported.  
This PR also includes some minor code clean up.
=> Remove Duplicate Logic for Post Type Attributes

lib/class-wp-json-posts-controller.php, tests/test-json-posts-controller.php
Fixes #856.
Correct request parameter conditional logic to look for the 'slug' parameter to update a Posts post_name property.
Includes unit test.
=> Passing a value for the slug parameter should update the post_name.

lib/class-wp-json-posts-controller.php, tests/test-json-pages-controller.php, tests/test-json-posts-controller.php
Currently we are relying on a lot of `! empty( $var )` checks which fail on setting `0` or `""` for valid values. I fixed up `menu_order`, `contnet`, `password` and `excerpt`
=> Empty checks in Posts Controller make setting values to Falsy impossible

README.md, plugin.php
Changes the project name in the Plugin name and the Readme title.
Part of #850
=> Change project name to WP REST API in plugin name and Readme title.

lib/class-wp-json-posts-controller.php, tests/test-json-posts-controller.php
Fixes #862. 
A post_type collection endpoint will no longer return a 404 status and a `json_invalid_query` WP_Error for valid queries that return 0 results.  
Now, valid queries that return 0 results will return a 200 status and an empty array.
=> Return 200 and an empty array for valid queries with 0 results.

lib/class-wp-json-terms-controller.php, tests/test-json-terms-controller.php
It's useful data that should always be included
I could've sworn there was an issue for this, but can't find it :/
=> Include the taxonomy in the term response

lib/class-wp-json-taxonomies.php
I was working on getting a little extra information into the taxonomy terms using the 'json_prepare_term' filter. It's surprising how difficult it is to get any extra information without the taxonomy slug. Really simple fix though.
=> Add taxonomy to term data list

lib/endpoints/class-wp-json-posts-controller.php, tests/test-json-pages-controller.php
Posts should only be accessible through `/wp/posts`. Pages should only be accessible through `/wp/pages`. Otherwise we're mixing up our data.
See #884
=> If post type doesn't match controller post type, throw 404

lib/endpoints/class-wp-json-posts-controller.php, tests/test-json-posts-controller.php
It's been a bug for a while...
See https://github.com/WP-API/WP-API/commit/7d66dde663d6d405a43331f6d575517fc94f286e#diff-5330db7df8462cb82a5542bbacfce38bL221
=> Updating another post field shouldn't change sticky status

lib/endpoints/class-wp-json-posts-controller.php, tests/test-json-posts-controller.php
If `type` is present in the request, safely ignore it
Fixes #884
=> Always defer to controller for post type

lib/class-wp-json-posts.php
`WP_JSON_Posts::get_post_types()` may have had some old code around. it was returning an object whose keys were the Posttype names, rather than an array of objects. Discovered this while exploring the client-js repo.
=> WP_JSON_Posts::get_post_types() should return array, not hash/object

lib/endpoints/class-wp-json-attachments-controller.php, lib/endpoints/class-wp-json-comments-controller.php, lib/endpoints/class-wp-json-terms-controller.php, plugin.php, tests/test-json-attachments-controller.php, tests/test-json-comments-controller.php, tests/test-json-terms-controller.php
Affects:
* `Attachment->post_id` => `Attachment->post`
* `Comment->post_id` => `Comment->post`
* `Comment->parent_id` => `Comment->parent`
* `Comment->user_id` => `Comment->user`
* `Terms->parent_id` => `Terms->parent`
See #605
=> Remove `_id` suffix from field names

lib/endpoints/class-wp-json-posts-controller.php
=> Allow `title` to be set to empty string in request

lib/endpoints/class-wp-json-posts-controller.php
The latter is intended for display, whereas the former is good for
sanitizing data
=> Use `wp_filter_post_kses()` instead of `wp_kses_post()` on insert

lib/endpoints/class-wp-json-posts-controller.php, tests/test-json-posts-controller.php
Fixes missing `/wp/` path in the 'href' values for the collection, up, and version-history `_links`.
=> Add missing core path to post endpoint link hrefs.

lib/infrastructure/class-wp-json-server.php
Simply check `$_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE']` and if it is set, use it as the request method.
=> Allow HTTP method to be overwritten by HTTP_X_HTTP_METHOD_OVERRIDE

lib/endpoints/class-wp-json-attachments-controller.php, tests/test-json-attachments-controller.php
`caption` is stored in `post_excerpt`, `description` is stored in
`post_content`. They were switched.
See
https://core.trac.wordpress.org/browser/trunk/src/wp-includes/media.php#L2701
=> Fix attachment caption and description fields

lib/infrastructure/class-wp-json-request.php, lib/infrastructure/class-wp-json-server.php
It's more semantic, and makes validation more accessible
See #871
=> Move validation to the `WP_JSON_Request` class

tests/test-json-posts-controller.php
Fixes spelling error noted by @rmccue in #938
=> Correct test method spelling of permission.

lib/class-wp-json-posts.php, tests/test-json-posts.php
During the split of the meta handling into it's own classes (#358) we broke documented functionality, including:
1. Allowing post_meta creation when creating a new post.
2. Allowing post_meta actions (add/edit/delete) when editing an existing post.
3. Returning post_meta values within the response for a post.
Additional unit tests needed here to make sure all edge cases are working as expected.
Originally identified by @tlovett1.
=> Fix BC Break with Post Meta Handling in Post Routes

lib/class-wp-json-comments.php, lib/class-wp-json-posts.php
Looks like with 6687602b73064d2e8ce6708b7018b2dd02bf2beb / 6d0ad766ca525c7a3aee921b66554ddf21a5c023 / 46498224624f419d915ce1a14afb399dc4d95850, we did two things which break BC: removed `date_tz` and `modified_tz`, and began stripping timezones from date strings.
While I agree these should be changed, they're a BC break in 1.x, so we need to revert at least the `*_tz` part.
I *think* we can get away with stripping timezone information, but we should check that.
=> Possible BC break with timezone handling

lib/endpoints/class-wp-json-posts-controller.php, tests/test-json-posts-controller.php
Currently we silently fail to not updating the date.
=> If an invalid date is supplied to create / update post, return an error

lib/endpoints/class-wp-json-comments-controller.php, tests/test-json-comments-controller.php
For comments, we currently have destructured author data in the following form:
```json
{
"author": "admin",
"author_email": "admin@example.com",
"author_url": ""
}
```
Why did we switch from structured data (`author: { ... }`) to destructured data in the first place? Is anyone opposed to changing that back?
Also fixes #893.
=> Change comment author to structured data

lib/class-wp-json-media.php
The get_post method does not return an array, but a WP_JSON_Response object. Because of this, the ID of the thumbnail is only to be found in the data variable of the class.
This PR fixes issue : #1009.
=> Bug fix: upload attachment error

lib/endpoints/class-wp-json-posts-controller.php, tests/test-json-posts-controller.php
Adds the `attachments` key to the `_links` object in a Post response for discoverability, which is also embeddable.  This does require allowing the `post_parent` query parameter to be public, which the WordPress.com API already allows: https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/.
=> Add embeddable attachments to Post response _links

lib/endpoints/class-wp-json-users-controller.php, tests/test-json-users-controller.php
The existing schema returned from `wp/users/schema` only included the following properties:
- id
- name
- email
- link
This adds the following missing properties to the schema:
- first_name
- last_name
- nickname
- slug
- url
- avatar_url
- description
=> Add missing response fields to the user schema.

lib/endpoints/class-wp-json-posts-controller.php, tests/test-json-posts-controller.php
From #961 we always trigger a 500 error is wp_insert_post() / wp_update_post() fails, however it's not neccesarily a problem with "us" it ould also be a problem with the request data.
I went through wp_insert_post() and put a check in for the only one which should be considered a 500 - which is a DB insert / update error. Also I made a tricky unit test to test this scenario.
=> Return correct response code from wp_insert_post() error

lib/endpoints/class-wp-json-posts-controller.php
protected methods are committments we don't want to make lightly.
See #1063
=> Remove unnecessary sticky posts abstraction

lib/class-wp-json-posts.php, tests/test-json-posts.php
Once a title has been set as non-empty further edits cannot set the title as empty. This fixes the problem with an `isset` check instead of `! empty`.
=> Allow empty titles to be set after initial title is set.

lib/endpoints/class-wp-json-controller.php, lib/endpoints/class-wp-json-posts-controller.php
Currently we pass the args as `array( 'title', 'author', ... );` which is not
the correct format. This Pull Request changes that to be `array( 'title' =>
array( ... ), ... )` which can / will be extended to add arg validation per
the enums / datatype defines in the schema.
=> Fix the format of the args when building them from the Schema

extras.php
Ensures the JSON endpoint URL is properly escaped when it's used in headers and RSD tags.
=> Ensure the JSON endpoint URL is properly escaped

lib/infrastructure/class-wp-json-server.php
The `json_pre_dispatch` and `json_post_dispatch` filters both have missing docs.
The `$result` parameter in the `json_post_dispatch` and `json_pre_serve_request` filters can be any object that implements `WP_HTTP_ResponseInterface`, not just a `WP_JSON_Response`, so that should be used as the parameter type in the docblock.
=> Correct a bunch of filter docs in WP_JSON_Server

lib/endpoints/class-wp-json-comments-controller.php, tests/test-json-comments-controller.php
If a comment author created a comment without the `moderate_comments`
capability, use context=view
Don't use `edit_comment` capability because `moderate_comments` can be
used to view the Comment list table without granting edit access
See #950, #702
=> Require `moderate_comments` capability to context=edit a Comment

lib/class-wp-json-media.php
=> Only use if it's not WP_Error, and get data from Response object

lib/endpoints/class-wp-json-posts-controller.php
I'd add test coverage, but mocking variable schemas is out of scope at
the moment
=> Fix copy pasta in the schema checks

lib/endpoints/class-wp-json-comments-controller.php, tests/test-json-comments-controller.php
Otherwise supplying `context=edit` grants unauthorized access to comment secrets
=> When `context=edit`, confirm user can `manage_comments`

lib/endpoints/class-wp-json-posts-controller.php, lib/endpoints/class-wp-json-revisions-controller.php, plugin.php, tests/test-json-posts-controller.php, tests/test-json-revisions-controller.php
Fixes #869, #855 
See #894, #314
=> Abstract revisions to dedicated controller; only include revisioned fields

plugin.php, tests/class-wp-test-json-controller-testcase.php, tests/test-json-server.php
Currently, developers must use the `wp_json_server_before_serve` hook to add
any new endpoints. This is very verbose and difficult to remember, I think it
would be better to have this named akin to `init` and `admin_init` hooks. In
the future, if the plugin switches to `wp_api` prefix, rather than `json` I
think we'd change this hook to `api_init` but for now I think it's best kept
inline with the rest of the naming conventions.
=> Rename the `wp_json_server_before_serve` to `wp_json_init`

lib/endpoints/class-wp-json-posts-controller.php
Practically speaking: a DELETE request to a post resource will ensure the post is trashed. If the post is already trashed, no change will occur. To permanently delete, pass force=true, and it will be permanently deleted regardless of status.
This is a change from the previous behaviour of the first DELETE trashing the post, and the second DELETE permanently deleting it.
See #789.
=> Ensure post deletion is idempotent

lib/endpoints/class-wp-json-comments-controller.php, lib/endpoints/class-wp-json-post-types-controller.php, lib/endpoints/class-wp-json-posts-controller.php, lib/endpoints/class-wp-json-taxonomies-controller.php, lib/endpoints/class-wp-json-users-controller.php
This completes the sanitizing outlined in https://github.com/WP-API/WP-API/pull/989
=> Sanitize args using new args API

lib/endpoints/class-wp-json-controller.php, lib/endpoints/class-wp-json-users-controller.php
More DRY and rebust as the args are hardlinked to the schema
=> Use the user fields from the item schema as the request args in route registration

.gitignore
They don't need to be tracked in version control
=> Ignore npm and composer vendor directories

lib/endpoints/class-wp-json-attachments-controller.php, lib/endpoints/class-wp-json-comments-controller.php, lib/endpoints/class-wp-json-controller.php, lib/endpoints/class-wp-json-posts-controller.php, lib/endpoints/class-wp-json-terms-controller.php, lib/endpoints/class-wp-json-users-controller.php
Picking up from #892 - now the endpoint args are specified from the schema, it pays to declare the readonly attribute, as these are ignored in the route's arg registration.
=> Readonly attribute in schema to exclude from args array

lib/endpoints/class-wp-json-posts-controller.php
We have to use a switch on the getting args from schema, as the `required`
flags in schemas should be ignored for update requests
=> Use the `required` flags from the schema for CREATE post

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-meta-controller.php, lib/endpoints/class-wp-rest-post-statuses-controller.php, lib/endpoints/class-wp-rest-post-types-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-revisions-controller.php, lib/endpoints/class-wp-rest-taxonomies-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-attachments-controller.php, tests/test-rest-comments-controller.php, tests/test-rest-meta-posts-controller.php, tests/test-rest-pages-controller.php, tests/test-rest-post-statuses-controller.php, tests/test-rest-post-types-controller.php, tests/test-rest-posts-controller.php, tests/test-rest-revisions-controller.php, tests/test-rest-taxonomies-controller.php, tests/test-rest-terms-controller.php, tests/test-rest-users-controller.php
Adds the endpoint versioning piece of #1119 
Core routes now use the `wp/v2` namespace.
=> Move all core routes to v2 namespace.

lib/endpoints/class-wp-rest-terms-controller.php, plugin.php, tests/test-rest-terms-controller.php
By passing the taxonomy to the controller, we can more easily allow
custom controllers for taxonomies, and for those custom taxonomies to
have custom schemas
Fixes #1061
See also #899
=> Retool `WP_REST_Terms_Controller` to follow Posts controller pattern

lib/infrastructure/class-wp-rest-request.php, tests/test-rest-request.php
This was the client know exactly which fields failed. See #1143
=> Include programmatically readable erros for validation

lib/endpoints/class-wp-rest-controller.php
This was when these lines were copied form the posts endpoint. Fixed to be
appropriatly named
=> Fix copy/pasted variable names

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
=> Only include `parent` in term response when tax is hierarchical

lib/endpoints/class-wp-rest-posts-controller.php, lib/infrastructure/class-wp-rest-response.php, tests/test-rest-pages-controller.php, tests/test-rest-posts-controller.php
Also handles adding `prev` link when outside of bounds
Removes `query_navigation_headers()` from `WP_REST_Response`, which was an oddball.
Fixes #890
=> Set pagination headers even when no found posts

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
=> Only link `author` when there's a valid author

lib/endpoints/class-wp-rest-comments-controller.php, tests/test-rest-comments-controller.php
Don't assume the `type` value is set since we don't require it.  
Fixes #1230  and adds test coverage.
=> Fix bug in creating comments if comment_type was not set

lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-users-controller.php
Changed the following fields to only display in the view or edit contexts:
- first_name
- last_name
- slug
- nickname 
Includes test coverage.
The `embed` context now only includes the following response fields:
`avatar_url`
`id`
`link`
`name`
`url`
`description`
=> Limit the Users response fields in the embed context

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
=> Return full post object when deleting post

lib/endpoints/class-wp-rest-posts-controller.php
We don't want it to be unique
Fixes #1193
=> Don't nullify `parent`

plugin.php
Rather than running the main query, let's run just before it.
Fixes #764.
=> Load the API much earlier

lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-users-controller.php
This will let the client more easily restore the data, should they need
to
See #1224
=> Return full user object when deleting user

lib/endpoints/class-wp-rest-posts-terms-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, plugin.php, tests/test-rest-posts-terms-controller.php, tests/test-rest-terms-controller.php
Should we allow `DELETE /wp/v2/posts/1/terms/post_tag` to remove all tags from the post?
Also should we allow `POST /wp/v2/posts/1/terms/post_tag` with body `{ ids: 1,2,3,4 }` to assign more than 1 term to a post?
See #1199
=> Add controller for a post's terms

lib/infrastructure/class-wp-rest-server.php, plugin.php, tests/test-rest-plugin.php, tests/test-rest-server.php
This is an alternate approach to #577 that we discussed.
Right now, we have the ability to take a site and discover whether it has the API enabled (and where it is). From there, you can see what routes are available on the site, but you can't actually tell what the site supports. For example, how do I know if the site has WooCommerce enabled? How do I know what versions of the API are supported?
In #577, we talked about a possible solution to this, which is to list out the core objects and where they're available in the API. This would allow for some feature detection based on what objects are available. However, this makes it a bit of a pain to actually use, since you still might not be able to understand the API. It doesn't really solve the core problem of discovery.
This PR tackles it …
=> List namespaces in the index

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-revisions-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php, lib/infrastructure/class-wp-rest-response.php, tests/test-rest-posts-controller.php, tests/test-rest-revisions-controller.php
This is a start to fix #1139.
Right now, this still uses the custom relation types, but next step is going to be trying switching that over.
I've also gone through and added a lot more fields to the embed context to make these links actually useful. Now you can go and get everything to render a single post nice and easily ([example post with embedding](https://gist.github.com/rmccue/1eba34f4ec6300e5513a)).
Also fixes #1289, fixes #1287
=> Sort out link relations and embedded data

plugin.php, tests/class-wp-test-rest-controller-testcase.php, tests/test-rest-server.php
I added inline docs to usages of `global $wp_rest_server` so its explicitly clear what the variable contains and so phpStorm can autocomplete methods of the class called using the global variable.
=> Inline docs for `global $wp_rest_server`

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
Validation is now handled by the schema
See #1062, #1063
=> Remove unnecessary `handle_format_param()` method.

lib/endpoints/class-wp-rest-posts-terms-controller.php, tests/test-rest-posts-terms-controller.php
But still default to ordering by `name`
Fixes #1214
=> Permit post terms to be queried by term order

lib/endpoints/class-wp-rest-posts-controller.php, plugin.php
Routing requests through the server in a RESTful manner permits us to
de-couple controllers from one another, permitting subclassing, etc. It
also ensures all of the appropriate permission and validation checks are
run on each internal request.
See #1218
=> Introduce `rest_do_request()` for making REST requests internally

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-comments-controller.php, tests/test-rest-users-controller.php
Previous changes in #1142 only addressed Posts.  This PR fixes the HTTP response code for update responses in Comments, Attachments, and Users.  I reviewed all endpoint controllers and these were the only remaining places this issue still existed.
=> Remove 201 status response for missed endpoints

extras.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-comments-controller.php, tests/test-rest-users-controller.php
- Add rest_get_avatars and deprecate rest_get_avatar
- Update Comment controller to use rest_get_avatars 
- Update Users controller to use rest_get_avatars
=> Return an array of avatar urls in different sizes for Comments and Users

README.md, extras.php, lib/infrastructure/class-wp-rest-request.php, lib/infrastructure/class-wp-rest-server.php
As we are using features / patches recently committed to WordPress Core, we
should let people know they should be using trunk.
=> Add a note mentioning WordPress Trunk should be used.

lib/endpoints/class-wp-rest-attachments-controller.php, tests/test-rest-attachments-controller.php
This functionality was only available in `update` for one reason or another.
Preusming this is an oversite.
=> Fix adding alt text to attachments on create

lib/class-wp-json-meta.php
When deleting or updating post meta, the verification of meta
belonging to object was failing because of "string - integer"
comparison.
=> Adds cast to integer in checking object metadata

plugin.php
Existing docs use "mixed" as the data type for return. That does not allow autocompletion doc reference for `rest_ensure_response()` in phpStorm, which made me sad.
=> Improve @return inline docs for rest_ensure_response()

lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-users-controller.php
This way we get to supply the clients with an `enum` of roles, also the field
for updating / creating a user is `role`. The maining question is whether to
remove support for multiple roles or not. Currently it's half of both.
Adding this PR to get the discussion moving!
=> Add `role` to schema for users

plugin.php, tests/test-rest-plugin.php
In the case where a develop has unregistered the post_tag / category taxonomy,
it currently produces PHP Notices.
=> Check taxonomies exist before trying to set properties

lib/infrastructure/class-wp-rest-server.php, tests/test-rest-comments-controller.php, tests/test-rest-posts-controller.php, tests/test-rest-request.php, tests/test-rest-server.php, tests/test-rest-users-controller.php
Fixes #248.
We need this to handle non-UTF8 text correctly.
Thanks @pento for his work on it!
=> Use wp_json_encode instead of json_encode

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-meta-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-attachments-controller.php, tests/test-rest-meta-posts-controller.php
This is a sweep for all the args to make sure we are snitizing where needed. The basic principle is sanitize evertyhing, however the shema does a bunch of stuff for us so we don't need to sepficy it in every case, such as:
- the schema is marked up as an `enum` as we have chcking to make sure values are only these
- the `format` is set in the schema whereby we have validation, for example, `date-time`
- the type is `integer`
Also, for `content` and `title` in the `wp/v2/posts` endpoint does not have any, as `wp_insert_post` handles that depending on whatever permissions the user has, so rather than replicating this, we just pass it through.
=> Sanitize pass on all controllers args

lib/endpoints/class-wp-rest-posts-controller.php
=> Re-enables the rest_insert_post action hook for WP_REST_Posts_Controller

lib/endpoints/class-wp-rest-comments-controller.php
The previous args had defaults of empty strings for `wp_allow_comment`, 
however I see this as an incorrect use of the abstraction. Args should not
have defaults just to please an underlaying function that expects those
values.
This also needed to move into `create_item` as the same default can not be
used for the `update_item` endpoint args.
=> Power the Comments endpoint args from the schema, like everything else

.travis.yml, bin/install-wp-tests.sh, lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-users-controller.php
Using the new WordPress `WP_User_Query` `has_published_posts` flag we can show only public users that would otherwise be exposed via authors on public posts on the `/wp/v2/users` endpoint.
See #839
=> Remove permissions checks from get users so we can show public users

lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-users-controller.php
Just now in #1397, we added the ability to list users with published posts at `/wp/v2/users`. Problem is, right now, it's exposing *all* user data (`context=view`), but users should only be able to access `context=embed`
Merging now to avoid security issues, but we can fix up the handling later.
cc @joehoyle
=> Don't expose non-public user information in the collection

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-users-controller.php
This should have been removed as part of #1348.  There is no need to set the Location header in update requests, because the response location isn't changing.
I found this while looking into #1436, and noticed that my response HTTP code when editing a user was `302` instead of the expected `200`.
=> Don't set the Location header in update responses

plugin.php, tests/test-rest-plugin.php
This breaks substantial amounts of the API, alas. See #1442.
Reverts WP-API/WP-API#1426
We'll need to fix this again at some point.
=> Revert "Ensure the REST API URL has a trailing slash"

.travis.yml
I [noticed](https://travis-ci.org/WP-API/WP-API/jobs/73981334) that you are running your tests on the [legacy infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy) on Travis and it looks like you don't use `sudo` so adding `sudo: false` to `.travis.yml` will tell Travis to run on docker container-based infrastructure.
=> Migrate to docker container-based travis

lib/infrastructure/class-wp-rest-server.php, plugin.php
See #865
This is a very simple approach. Essentially: if you return a list from your endpoint, apply `embed_links` to the items inside that rather than the top-level.
If we switch collections to objects, we can handle this differently, but that's a separate issue at #1196.
=> Embed links inside items in a collection

lib/endpoints/class-wp-rest-attachments-controller.php, tests/test-rest-attachments-controller.php
Currently it builds this with str_replace which can be error prone, and 
doesn't file the expected `image_downsize` filter than a lot of media related
plugins use to alter the image.
=> Use wp_get_attachment_image_src() on the image sizes in attachments

lib/infrastructure/class-wp-rest-server.php
We should allow linking with the `view` context explicitly set. This allows you to build custom endpoints that link out to other collections and include the full data when embedding.
A good use for this is having your Blog page link to the full posts collection to allow loading in the title/permalink as well as the posts to display on the page.
=> Make the embed context a default, not forced

lib/endpoints/class-wp-rest-posts-terms-controller.php, lib/endpoints/class-wp-rest-terms-controller.php
* When the client attempts to create a term that already exists, we should return to them the `term_taxonomy_id` as part of the error data, NOT the `term_id`. The `term_id` is useless and arguably dangerous to the client, since they may attempt to use it elsewhere (ahem ;)).
* When associating terms, we must resolve the `term_id` from the client-provided `term_taxonomy_id`. Wordpress core uses the `term_id` to make the association.
=> Resolves two issues with term creation and term assocaition

plugin.php
In cases where I'm writing a full bespoke/whitelabelled API rather than adding to WordPress's routes, or them even being available, I want to not use namespaces at all.
This is probably controversial - but point being I want my api at `myserviers.com/api` for better or worse. (In this specific case I'm migrating from another API system, so I need the URLs to match the old ones as it's a drop in replacement).
In this case, it's pretty easy for us to support this by just checking if a namespace was not-empty and don't add the double slashes if so.
=> If not namespace is provided, don't create double slashes

plugin.php, tests/test-rest-plugin.php
See #1426. This one shouldn't accidentally break embedding; tested locally and it's all working.
Props @danielpunkass for the bug report and initial patch, plus the unit tests which I've borrowed here.
=> Fix trailing slashes on non-pretty permalinks

lib/infrastructure/class-wp-rest-server.php, tests/test-rest-server.php
Turns out we weren't running `response_to_data` previously. Whoops!
Fixes #1288.
=> Show links on embeds

lib/endpoints/class-wp-rest-attachments-controller.php, tests/test-rest-attachments-controller.php
Attachments controller is passing the entire $_FILES array to wp_handle_update, when it should only pass a single entry.
This commit fixes it by using the 'file' entry in $_FILES array, as stated in the documentation.
See http://wp-api.org/#media_create-an-attachment
=> Fix file upload for attachments.

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
Matches the logic currently in WP_REST_Posts_Controller::get_item() and WP_REST_Posts_Controller::delete_item()
Fixes #1258
=> WP_REST_Posts_Controller::update_item() should check the ID correlates with proper type

lib/infrastructure/class-wp-rest-response.php, tests/test-rest-server.php
Currently there's no way a filter can easily remote link relations via the reponse object. This allows that!
=> Allow removing links froma response object

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
Corrects the `replies` link in a single Post response to use the correct query arg.
Fixes #1525
=> Fix bug in post comments link query arg

plugin.php
Currently when you have a page with the slug wp-json-info it will show the API instead of the page.
=> Don't link everything with rest_get_url_prefix() to the API.

extras.php
* Add a missing hook doc.
* xtras.php:185:	return apply_filters( 'rest_avatar_sizes', array( 24,
48, 96 ) );
=> Hook docs- extras.php

lib/infrastructure/class-wp-rest-request.php
=> Hook Docs: Add missing hook docs in lib/infrastructure/class-wp-rest-request.php

lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-comments-controller.php, tests/test-rest-posts-controller.php, tests/test-rest-terms-controller.php, tests/test-rest-users-controller.php
When a post or a comment is deleted, return a flag to say whether it's been trashed or properly deleted.
See #1260.
=> Return the trashed status of delete posts/comments

.gitignore, lib/endpoints/class-wp-rest-users-controller.php
See https://github.com/WP-API/WP-API/issues/1549.
* Add some missing hook docs
* Spacing, punctuation cleanup as per standard
* Change second do_action from `rest_insert_user` to `rest_update_user` as
its in the update function
* added some todo notes, I don’t understand what the final false
variable is for, maybe its needed?
=> Hook Docs for lib/endpoints/class-wp-rest-users-controller.php

lib/endpoints/class-wp-rest-attachments-controller.php
* Add hook docs for `rest_prepare_attachment`
=> Hook docs: lib/endpoints/class-wp-rest-attachments-controller.php

lib/endpoints/class-wp-rest-posts-controller.php
Rather than linking to `wp/v2/media?post_parent=<id>`, we should be linking directly to the featured image, with a secondary link out to the former.
Fixes #1476.
=> Change featured image links

tests/test-rest-comments-controller.php
Create a new user to create the comment in the assign different user test
Don't re-use `$this->subscriber_id` and trigger a wp_die from `check_comment_flood_db()`
Intended to fix the unit tests failing in Travis with:
```
1) WP_Test_REST_Comments_Controller::test_create_item_current_user
WPDieException: You are posting comments too quickly. Slow down.
```
=> Hotfix Comment Tests

lib/infrastructure/class-wp-rest-server.php
=> Fix misspelling of since tag in `WP_Rest_Server` docs

lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-controller.php, lib/endpoints/class-wp-rest-meta-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-comments-controller.php
Now get_endpoint_args_for_item_schema() will take a $method param which is used to determin if the endpoint args should include the `required` and `default` parameters.
We could have potentially handled this at the WP_REST_Server level, however the "incorrect" part here is generating the args from the schema. `get_endpoint_args_for_item_schema` is really shorthand for writing out the args for the endpoint - in the case we were writing those by hand, we wouldn't be passing `default` and `required` in the case of `EDITABLE` endpoint args.
=> Modify get_endpoint_args_for_item_schema to handle required/default

lib/infrastructure/class-wp-rest-server.php
In 6388ce46530bfb2, logic was changed to rely on the handler data
directly. The capture of supported methods into a local variable
is no longer necessary.
=> Remove unused `$supported` methods variable

lib/endpoints/class-wp-rest-attachments-controller.php, tests/test-rest-attachments-controller.php
Upload from file checking for header 'CONTENT_MD5', but all headers are canonicalized by WP_REST_Request::canonicalize_header_name(), so this header is never present.
Upload from data correctly checks for 'content_md5' header.
Also, upload from file tries to handle the header as a string instead of as an array.
Surprisingly, the test case for 'bad MD5 header' is incorrectly checking for a 201 return, instead of a 412.
This commits fixes the MD5 check on upload from file by copying the way it is handled by upload from data.
=> Fix MD5 check on file uploads.

plugin.php, tests/test-rest-plugin.php
WordPress 4.4 includes a 'register_post_type_args' filter
which can be used instead of directly modifying the global.
Previously, the function was hooked to `init` with a
priority of 11, but it is now set to 10 on the new filter.
Added unit tests to confirm the arguments are added
to each type.
Fixes #1588.
=> Switch to register_post_type_args filter.

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
* Add missing collection args details to the Terms Controller
* fill-in details for the `per_page`, `page`, `hide_empty`, and `search` args that are already handled in the get_items method
* add a `sanitize_callback` to the `order` arg
* add a `sanitize_callback` and add missing valid values to the enum array for the `orderby` arg
* Don't hardcode the `hide_empty` collection arg to being false in `get_items` method
=> Add Terms Controller Collection Args Details

lib/endpoints/class-wp-rest-users-controller.php
The default context for a single user request is `embed`.  Whereas the default context for the users collection is `view`.  
This just adds the `embed` context as a specified option for users collection requests.
=> Add the embed context to Users collection query params

lib/infrastructure/class-wp-rest-server.php
`EDITABLE` is an alias for POST, PUT, and PATCH, not GET
=> Correct methods in WP_REST_SERVER::EDITABLE description

tests/test-rest-plugin.php
Core's test suite began backing up and restoring public and private
query vars in https://core.trac.wordpress.org/changeset/35258/ This
means we need to register our custom query var each time we want to
reference it.
=> Fix failing test

package.json
Ran `grunt phplint` before and after upgrading package and output remains the same (no linting errors).
GPL-2.0 license added to avoid NPM warning when running NPM install.
=> Add license in package.json, bump phplint package version

lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-users-controller.php
`user_nicename` is a public attribute, used in user URLs, so this is
safe data to present
Fixes #1611
=> Expose `slug` in `embed` context for Users

plugin.php
We should look at fixing this, but the core commit at 
https://core.trac.wordpress.org/changeset/35353 caused a fatal in several
cases.
=> Include the admin functions for the API

extras.php
This function is included in WP 4.4, but we need to maintain support for
4.3
=> Compat shim for `wp_is_numeric_array()`

extras.php
It was renamed in core, but we need to make sure 2.0beta* endpoints
dependent on it don't fatal
=> Add compat shim for renamed `rest_mysql_to_rfc3339()`

tests/test-rest-comments-controller.php
We'll need to revisit this after `wp_die()` handling is added.
See #1660, #790
=> Add a (skipped) test for creating two comments quickly

lib/endpoints/class-wp-rest-attachments-controller.php, tests/test-rest-attachments-controller.php
For image attachments, `media_details` includes a `sizes` array of image
sizes, which is useful for templating.
Previously #1582
=> Include `media_details` attribute for attachments in embed context

plugin.php
This commit Corrects the DocBlocks for Requires and Includes in accordance with WP PHP documentation standards https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#3-requires-and-includes
=> Correct the DocBlocks for Requires and Includes

lib/endpoints/class-wp-rest-controller.php
In accordance with WP PHP documentation standards Add Periods to end comments, @params and @returns
=> Add Periods to end comments, @params and @returns

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-users-controller.php, plugin.php
As this was removed from core, we hastily added it back, however I dug through all the places where we actually need any functions only loaded in the admin in #1686 and it's not so bad.
=> Remove admin.php include

lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-comments-controller.php
It can be useful for determining the absolute time for the resource.
`date_gmt` was set for `edit` context only in
29c768b93a51a14cdf4031493f03f798cc1f1730 and
a12c23a76a747a074083094e76dd169a2b335448
See #1675
=> Expose `date_gmt` for `view` context of Posts and Comments

lib/endpoints/class-wp-rest-posts-terms-controller.php
Only call the permissions check from terms controller
See #1583
=> Avoid expensive call to get_item() in post terms controller

lib/endpoints/class-wp-rest-posts-controller.php
`get_post_format_slugs` returns `array( 'audio' => 'audio' )` for some odd
reason, we want it to be a numeric array of strings.
=> Fix the post formats enum to be an array of strings

lib/endpoints/class-wp-rest-posts-controller.php
They're the date, but in the site's timezone.
Fixes #1675
=> Clarify what `date` and `modified` actually are

lib/endpoints/class-wp-rest-controller.php
If you use `register_api_field` with an array of object types, then there does not seem to be a decent way to know what context these callbacks are being called from. This update passes the object type through to the callback function.
=> Provide object type as callback argument

.travis.yml
We only care to get emails when the build fails.
=> Make Travis notifications less noisy

.travis.yml, bin/install-wp-tests.sh, plugin.php, tests/test-json-plugin.php
When sites using WP-API v1.x upgrade to WordPress 4.4, they'll expect the plugin to continue working.
Originally https://core.trac.wordpress.org/ticket/34399
=> Prioritize WP-API v1.x rewrite rules over core REST API

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
=> Change link relations to use api.w.org

lib/endpoints/class-wp-rest-posts-controller.php
The value is still set if `&filter` is passed, but `array_merge()` will
error if `$request['filter']` isn't an array.
From #1733
=> Only process `filter` when it's an array

lib/endpoints/class-wp-rest-meta-controller.php
=> Change int to integer for WP_REST_Controller::validate_schema_property()

lib/endpoints/class-wp-rest-attachments-controller.php
We're using functions that are only included in admin scope.
Fixes #1755
Introduced in #1696
=> Include admin utilities in one more place

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
Clients should only be able to request categories from the category route, and tags from the tag route
Fixes #1763
=> Don't permit requesting terms cross routes

lib/endpoints/class-wp-rest-users-controller.php, wp-api.js
The count query for the users should just pass the $fields => 'ID' param,
otherwise WordPress will init a WP_User object for every user on the site,
basically killing it.
=> Set the fields to 'id' fixing large memory usage

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
Right now, updating posts with quotes causes slashes to be saved to the db, as
wp_update_post does `wp_slash` on already slashed data if you pass it an
object.
I'm not sure if this is the best fix, but the unit test illustrates the issue.
=> Post updates should expect slashed data

lib/endpoints/class-wp-rest-meta-controller.php
When submitting a Post Meta Create request, the response contains
a Location header with 'wp/v2' missing from the path.
Currently either `$this->parent_base` returns the wrong (empty) base,
or `wp/v2/` is missing from the base when setting the Location header
for a Post Meta Create response.
c.a.w.w.v.Client.debugRequest() - Request Entity:\
<POST http://johan-wp/wp-json/wp/v2/posts/3766/meta,\
{key=Gomxw, value=bLfaU},\
{Authorization=[Basic am9oYW4ubXluaGFyZHQ6d29yZHByZXNzIQ==]}>
c.a.w.w.v.Client.debugHeaders() - Response Headers:
...
c.a.w.w.v.Client.lambda$debugHeaders$8() - \
Location -> [http://johan-wp/wp-json/posts/3766/meta/11965]
...
c.a.w.w.v.Client.debugRequest() - Request Entity:\
<POST http://johan-wp/wp-json/wp/v2/posts/3766/meta,\
{key=Gomxw, value=bLfaU},\ …
=> Missing 'wp/v2' in path in Location Response header

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
Sticky posts are unrestful functionality. But, they can be re-enabled
for posts only with `filter[ignore_sticky_posts]=false`
Fixes #1623
=> Ignore sticky posts by default

lib/endpoints/class-wp-rest-attachments-controller.php, tests/test-rest-attachments-controller.php
=> Include `full` image size in attachment `sizes` attribute

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-meta-controller.php, lib/endpoints/class-wp-rest-meta-posts-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-posts-terms-controller.php, lib/endpoints/class-wp-rest-revisions-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php
`ID` is an implementation artifact. Our Resources use `id`.
=> In text strings, use `id` instead of `ID`

.travis.yml
`latest` is now WordPress 4.4. We want to ensure 4.3 support for another
beta or two, so we need to make sure tests continue to pass.
Related #1794
=> Include WordPress 4.3 in the test matrix

lib/endpoints/class-wp-rest-attachments-controller.php, tests/test-rest-attachments-controller.php
Underscored keys are easier to access in some languages (e.g. JS)
Fixes #1807
=> Ensure `attachment.sizes[]` use `mime_type` instead of `mime-type`

lib/endpoints/class-wp-rest-attachments-controller.php, lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-meta-posts-controller.php, lib/endpoints/class-wp-rest-post-statuses-controller.php, lib/endpoints/class-wp-rest-post-types-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-posts-terms-controller.php, lib/endpoints/class-wp-rest-revisions-controller.php, lib/endpoints/class-wp-rest-users-controller.php, plugin.php, tests/test-rest-attachments-controller.php, tests/test-rest-comments-controller.php, tests/test-rest-meta-posts-controller.php, tests/test-rest-post-statuses-controller.php, tests/test-rest-posts-controller.php, tests/test-rest-revisions-controller.php, tests/test-rest-users-controller.php
This function produces a contextually-specific HTTP error code based on
whether the user is logged in. It should be used when producing an error
from a failed `current_user_can()` check, because it's helpful to the
client to be able to distinguish between 401 and 403
Fixes #757
Fixes #1665
=> Introduce `rest_authorization_required_code()`

lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-posts-terms-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, plugin.php, tests/test-rest-plugin.php, tests/test-rest-posts-controller.php, tests/test-rest-posts-terms-controller.php, tests/test-rest-terms-controller.php
Tags are now accessible at `/wp/v2/tags`, and categories accessible at
`/wp/v2/categories`. Post terms reside at `/wp/v2/posts/<id>/tags` and
`/wp/v2/<id>/categories`
Although this introduces the risk of collision between custom post types
and custom taxonomies, said collision isn't currently handled in
WordPress core. Developers can use `rest_base` to ensure CPTs and
taxomonies have distinct slugs.
Fixes #829
=> Move tags and categories to top-level endpoints

lib/endpoints/class-wp-rest-taxonomies-controller.php, tests/test-rest-taxonomies-controller.php
Changes `$data` from an array to WP_REST_Response when
supplied to `rest_prepare_taxonomy`
Fixes #1381
=> Link taxonomies to their associated collections

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
=> Ensure Terms link to their appropriate Taxonomy

extras.php
`json_get_timezone()` was only ever used in v1. This function causes
fatals, and shouldn't be used.
Fixes #1438
=> Remove `rest_get_timezone()`

lib/endpoints/class-wp-rest-taxonomies-controller.php, tests/test-rest-taxonomies-controller.php
This is consistent with `/wp/v2/types` and `/wp/v2/statuses`
Fixes #1819
=> Return object for requests to `/wp/v2/taxonomies`

plugin.php, tests/test-rest-attachments-controller.php, tests/test-rest-comments-controller.php, tests/test-rest-post-statuses-controller.php, tests/test-rest-post-types-controller.php, tests/test-rest-posts-controller.php, tests/test-rest-revisions-controller.php, tests/test-rest-users-controller.php
Introduces a `register_api_field()` function for backwards compat, which
calls `_doing_it_wrong()`
Fixes #1321
=> Rename `register_api_field()` to `register_rest_field()`

lib/endpoints/class-wp-rest-comments-controller.php, tests/test-rest-comments-controller.php
If it's enabled, require users to be logged in to comment.
=> Respect core's `comment_registration` setting

wp-api.js
* Initial pass at bringing the library up to date
* Correct model endpoints that have changed
* Verified all models read correctly
* Verified Post create, read, destroy (trash)
* Clean up doc block language for models
* Add additional JSDOC3 Doc Blocks for models
* rename internal BaseModel to WPApiBaseModel
* user model defaults to 'me' route if no user id is passed
* remove slug default from Post model, passing a blank slug was causing Create to fail.
* Consider eliminating defauls, the api already has defaults?
* Correct overriding of 'delete', backbone model funciton is `destroy`
=> Bring the wp-api.js library up to date for v2 of the REST API

lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-controller.php, lib/endpoints/class-wp-rest-meta-controller.php, lib/endpoints/class-wp-rest-post-statuses-controller.php, lib/endpoints/class-wp-rest-post-types-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-posts-terms-controller.php, lib/endpoints/class-wp-rest-revisions-controller.php, lib/endpoints/class-wp-rest-taxonomies-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php
=> Consistently indicate `context` argument for GET requests

lib/endpoints/class-wp-rest-posts-terms-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-posts-terms-controller.php, tests/test-rest-terms-controller.php
See #1628
We can now treat the term_id as unique across taxonomies, this simplifies things a good amount.
=> Change terms endpoints to use term_id not tt_id

lib/endpoints/class-wp-rest-taxonomies-controller.php, tests/test-rest-taxonomies-controller.php
It's consistent with how we're exposing post types in the API
Fixes #1836
=> Change taxonomies' `post_type` argument to `type`

lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-controller.php, lib/endpoints/class-wp-rest-meta-controller.php, lib/endpoints/class-wp-rest-post-statuses-controller.php, lib/endpoints/class-wp-rest-post-types-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-posts-terms-controller.php, lib/endpoints/class-wp-rest-revisions-controller.php, lib/endpoints/class-wp-rest-taxonomies-controller.php, lib/endpoints/class-wp-rest-terms-controller.php, lib/endpoints/class-wp-rest-users-controller.php, tests/class-wp-test-rest-controller-testcase.php, tests/test-rest-attachments-controller.php, tests/test-rest-comments-controller.php, tests/test-rest-meta-posts-controller.php, tests/test-rest-pages-controller.php, tests/test-rest-post-statuses-controller.php, tests/test-rest-post-types-controller.php, tests/test-rest-posts-controller.php, tests/test-rest-posts-terms-controller.php, tests/test-rest-revisions-controller.php, tests/test-rest-taxonomies-controller.php, tests/test-rest-terms-controller.php, tests/test-rest-users-controller.php
Abstracting this to a common method lets us reuse it between `GET`
collection and `GET` single instance
See #1706
=> Introduce `get_context_param()` for getting the magical context param

lib/endpoints/class-wp-rest-post-types-controller.php, lib/endpoints/class-wp-rest-taxonomies-controller.php, tests/test-rest-post-types-controller.php, tests/test-rest-taxonomies-controller.php
`collection` should go to the collection of types and taxonomies,
respectively. While imperfect, `item` is the best definition we have for
the link to the collection of items.
From https://github.com/WP-API/WP-API/pull/1829#issuecomment-163777701
=> Fix link relations for individual types and taxonomies

lib/endpoints/class-wp-rest-posts-controller.php
=> Prevent error notice when `show_in_rest` isn't set for a post type

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
This is an underlying implementation detail. Post formats aren't a custom taxonomy in the eyes of the REST API.
Fixes #1448
See https://github.com/WP-API/WP-API/issues/1448#issuecomment-128825059
=> Don't include `post_format` as a term `_link` for Posts

tests/test-rest-attachments-controller.php, tests/test-rest-comments-controller.php, tests/test-rest-meta-posts-controller.php, tests/test-rest-pages-controller.php, tests/test-rest-post-statuses-controller.php, tests/test-rest-post-types-controller.php, tests/test-rest-posts-controller.php, tests/test-rest-taxonomies-controller.php, tests/test-rest-terms-controller.php, tests/test-rest-users-controller.php
`dispatch()` has only returned `WP_REST_Response` for quite a while.
=> Remove unneeded calls to `assertNotInstanceOf` and `rest_ensure_response`

lib/endpoints/class-wp-rest-post-types-controller.php, lib/endpoints/class-wp-rest-taxonomies-controller.php, tests/test-rest-post-types-controller.php, tests/test-rest-taxonomies-controller.php
Use custom `https://api.w.org/items` relation instead of incorrect
`item` relation.
See https://github.com/WP-API/WP-API/pull/1846#issuecomment-164086269
=> Fix link relations for individual types and taxonomies, part 2

.gitmodules, .travis.yml, bin/readme.txt, plugin.php
WordPress 4.4 is now the latest stable release
Fixes #1794
=> Remove compatibility repo for WordPress 4.3

lib/endpoints/class-wp-rest-comments-controller.php, tests/test-rest-comments-controller.php
`manage_comments` doesn't exist; `moderate_comments` does
=> Fix invalid capability for comments get items permissions callback

lib/endpoints/class-wp-rest-taxonomies-controller.php, tests/test-rest-taxonomies-controller.php
=> Add `edit` context for `wp/v2/taxonomies`; require `manage_terms` cap

lib/endpoints/class-wp-rest-users-controller.php
Related to #1708, this adjusts the order of the User resources so that `id` is the first property and the remaining properties match the Schema order.
=> Change order of Users response to match schema order

lib/endpoints/class-wp-rest-posts-controller.php, lib/endpoints/class-wp-rest-users-controller.php, tests/test-rest-posts-controller.php
Use the `posts_per_page` and `paged` values from `$query_args` instead of only from the shortened Request params when calculating the `X-WP-TotalPages` header as well as the `prev` and `next` link headers.  This prevents incorrect headers when either the `filter[posts_per_page]` or `filter[paged]` request params are used, as well as hooks into the `rest_post_query` filter.
Fixes #1876
=> Adjust Posts Pagination Headers for `filter` Params

lib/endpoints/class-wp-rest-controller.php
While probably negligible, casting the integer `(int)` is faster than using `intval()`. Just an idea.
=> Cast integer with (int) over intval for speed

lib/endpoints/class-wp-rest-comments-controller.php, lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-comments-controller.php, tests/test-rest-posts-controller.php
* Remove unused date error handling for invalid Comment & Post dates (handled by schema validation)
* Add unit tests for updating a comment with invalid dates
* Add unit test for creating a comment with an invalid date
* Add unit tests for updating Posts with invalid dates
* Add `readonly` attribute to the modified dates for Posts, since WP doesn't allow them to be set in `wp_insert_post()` or `wp_update_post()`
* Add a unit test to make sure a readonly property (like `modified`) is ignored per https://github.com/WP-API/WP-API/commit/0e8364ea5c59a9ce03a85c243c690101a5213c2f
Replaces #1881
=> Remove extra date handling errors and expand on unit tests

lib/endpoints/class-wp-rest-posts-terms-controller.php
Because the same callback is used for create and delete,
`manage_item_permissions_check()` makes more sense than
`create_item_permissions_check()`
=> Rename post terms create/delete permissions callback

lib/endpoints/class-wp-rest-terms-controller.php
Adds a filter for the `prepared_args` before passing them to `get_terms()` (matching behavior to the Posts and Users collections), and then adjusting the pagination headers so that the `prepared_args` are used instead of only the Request params.  
See #1878
=> Allow Terms Collection Params to be Filtered

tests/test-rest-posts-controller.php
It's precise-enough for the needs of this test, and prevents the test
from randomly failing when the database slows down.
Fixes #1935
=> Use Y-m-d for comparing modified times

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-pages-controller.php, tests/test-rest-posts-controller.php
These private query variables should be accessible to CPTs when a user
can't create normal posts.
=> Defer to `edit_posts` of the custom post type

lib/endpoints/class-wp-rest-posts-terms-controller.php, tests/test-rest-posts-terms-controller.php
=> Check `assign_terms` cap for taxonomy when managing post terms

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
* Use `show_in_rest` instead of `public`; rename method.
* Return more descriptive `WP_Error` responses.
* Move 404 check for update term for consistency.
=> Clean up permissions checks in `WP_REST_Terms_Controller`

lib/endpoints/class-wp-rest-comments-controller.php
While this change doesn't have any functional changes, it's in line with
our pattern throughout the rest of the codebase.
See https://github.com/WP-API/WP-API/pull/1932#discussion_r48764666
=> Don't include method and URL in internal `WP_REST_Request` (Comments)

lib/endpoints/class-wp-rest-posts-controller.php
If attempting to submit a `password` consisting of an empty string while also submitting true value for `sticky`, the API is returning an error:
> A post can not be sticky and have a password.
I believe it should be considering an empty string to be as if the value was not set.
=> Flag sticky if password not empty instead of isset

lib/endpoints/class-wp-rest-users-controller.php
Without this file loaded, the `DELETE` request will fatal.
Fixes #1957
=> Load `wp-admin/includes/user.php` to expose wp_delete_user()

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
Instead of silently discarding them.
Discovered in #1961
Related #924
=> Ensure `GET /wp/v2/posts` respects `order` and `orderby` params

.travis.yml
Ensures only one build is created on pull requests, instead of two.
See https://github.com/alleyinteractive/wordpress-fieldmanager/pull/430#issuecomment-169696750
=> Cut Travis' load in half

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-posts-controller.php
Permits limiting results to a specific defined set
See #1668
=> Add `include` parameter to `GET /wp/v2/posts`

lib/endpoints/class-wp-rest-terms-controller.php, tests/test-rest-terms-controller.php
`page`, `per_page` and `search` are inherited from the base controller
=> Remove duplicated query params from Terms controller

lib/endpoints/class-wp-rest-comments-controller.php, tests/test-rest-comments-controller.php
Also explicitly declares `order` and `orderby` parameters
See #1668
=> Add `include` parameter to `GET /wp/v2/comments`

lib/endpoints/class-wp-rest-posts-controller.php, tests/test-rest-attachments-controller.php
=> Permit logged-in users to query for media
